### ISSUE TITLE
No output using NVIDIA graphics card, also Lua config seems to not work properly

### ISSUE THREAD

**Issue by vnepogodin** [pinnacle-comp/pinnacle#113]
Either launched with udev or winit, it gives zero output to monitors.
monitors appears to have no connection attached.
Also doesn't respond to keybinds, not able to close  pinnacle via keybind from example config

built from https://github.com/pinnacle-comp/pinnacle/commit/1774f2f268d4434dab366d1c74b4d5a4fdf12936

In winit appears no render :
![image_2023-12-18_03-00-35](https://github.com/pinnacle-comp/pinnacle/assets/37552959/b20f0c9c-85e3-46ba-a685-00bbdbab95d9)

winit logs with default lua config:
`PINNACLE_CONFIG="./api/lua/example_config.lua" RUST_BACKTRACE=full RUST_LOG=trace cargo r -r -- --winit &> winit_verbose.log`
[winit_verbose.log](https://github.com/pinnacle-comp/pinnacle/files/13698092/winit_verbose.log)

**Comment by Ottatop** [comment]
Is that Hyprland in the background? I've just discovered that Pinnacle does not work when run inside of Hyprland.

Additionally, from your log I can see that no keybinds from the config are getting received by the compositor.

So two things:
1. Can you run it in a tty or from something other than Hyprland and try the metaconfig-defined quit keybind (`Ctrl + Alt + Shift + Escape`) instead of the one in the example config? That will confirm whether or not my Hyprland theory is correct.
2. Can you give me your distro and the config in your `~/.config/pinnacle` directory?

Also that command you used is really old, `PINNACLE_CONFIG` no longer does anything so that just caused your `init.lua` in  `~/.config/pinnacle` to run.

**Comment by vnepogodin** [comment]
> 1. Can you run it in a tty or from something other than Hyprland and try the metaconfig-defined quit keybind (`Ctrl + Alt + Shift + Escape`) instead of the one in the example config? That will confirm whether or not my Hyprland theory is correct.

I've tried both udev(from tty), winit(with Sway and Hyprland). for winit equal result
udev just doesn't display anything.

> 2. Can you give me your distro and the config in your `~/.config/pinnacle` directory?

my distro is CachyOS. and my `init.lua` https://paste.cachyos.org/p/a49caf1.lua 

> Also that command you used is really old, PINNACLE_CONFIG no longer does anything so that just caused your init.lua in ~/.config/pinnacle to run.

Oh alright

**Comment by Ottatop** [comment]
Ok I'm unable to reproduce any issues in a CachyOS VM so I'm going to need some more info.

Can you run `PINNACLE_CONFIG_DIR=./api/rust cargo run &> rust.log` and let it run for a minute for the Rust config to build and give me the log?

Also can you give me any logs in `~/.local/state/pinnacle`? Maybe there's something useful there.

My hunch is that the compositor is blocking somewhere which is why it isn't getting any keybinds, why your log shows that the config is blocked trying to read from the socket, and why nothing is getting output by the compositor. If it did, I'm not sure what's causing it.

**Comment by vnepogodin** [comment]
> Can you run `PINNACLE_CONFIG_DIR=./api/rust cargo run &> rust.log` and let it run for a minute for the Rust config to build and give me the log?

`PINNACLE_CONFIG_DIR=./api/rust RUST_BACKTRACE=full RUST_LOG=trace cargo r &> rust.log` in tty
[rust.log](https://github.com/pinnacle-comp/pinnacle/files/13708466/rust.log)

> Also can you give me any logs in `~/.local/state/pinnacle`? Maybe there's something useful there.

[2023-12-18-20.pinnacle.log](https://github.com/pinnacle-comp/pinnacle/files/13708474/2023-12-18-20.pinnacle.log)

**Comment by Ottatop** [comment]
What GPU are you using?

I'm seeing events from `smithay::backend::drm::device::DrmDeviceNotifier` when I run it that don't appear in your log, so maybe it's a GPU or driver thing. It could also be something completely different but I have no idea what else would prevent monitor output.

**Comment by vnepogodin** [comment]
> What GPU are you using?
> 
> I'm seeing events from `smithay::backend::drm::device::DrmDeviceNotifier` when I run it that don't appear in your log, so maybe it's a GPU or driver thing. It could also be something completely different but I have no idea what else would prevent monitor output.

I have NVIDIA gpu with latest driver `545.29.06`

**Comment by Ottatop** [comment]
Unfortunately I don't have much knowledge in dealing with vendor-specific stuff nor do I have an NVIDIA graphics card, so this issue might take a while to be resolved, sorry.

You can try other Smithay-based compositors listed on [Smithay's README](https://github.com/Smithay/smithay#other-compositors-that-use-smithay) to see if it's a driver/dependency issue you have with the underlying compositor library, but I *doubt* that because other Wayland compositors on your system work just fine, it's most likely something I've done wrong.

**Comment by vnepogodin** [comment]
> Unfortunately I don't have much knowledge in dealing with vendor-specific stuff nor do I have an NVIDIA graphics card, so this issue might take a while to be resolved, sorry.
> 
> You can try other Smithay-based compositors listed on [Smithay's README](https://github.com/Smithay/smithay#other-compositors-that-use-smithay) to see if it's a driver/dependency issue you have with the underlying compositor library, but I _doubt_ that because other Wayland compositors on your system work just fine, it's most likely something I've done wrong.

yeah I can confirm anvil works fine at least with winit.
![image](https://github.com/pinnacle-comp/pinnacle/assets/37552959/f3dddec4-9589-410a-b947-d08e5613e996)

so something has to be wrong in the pinnacle, I might try to debug and send PR on holidays

as reference output of anvil (https://paste.cachyos.org/p/7418f5c.log)

**Comment by vnepogodin** [comment]
@Ottatop 

I've fixed it by updating dependencies(including smithay to latest commit) of pinnacle.

lua config works fine, output also displays

**Comment by Ottatop** [comment]
It *would* be something really obvious that I didn't think of, huh.

I'll spin off another issue for the really low frame rate.
